# App1 staging values
appName: app1

replicaCount: 1

image:
  repository: gcr.io/your-project/app1
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

configMap:
  enabled: true
  data:
    APP_ENV: "staging"
    LOG_LEVEL: "debug"
