# App1 production values
appName: app1

replicaCount: 3

image:
  repository: gcr.io/your-project/app1
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

configMap:
  enabled: true
  data:
    APP_ENV: "production"
    LOG_LEVEL: "info"
